;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 1.3.40
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

 (defpackage :netcdf
	(:use :cffi :cl))
 (in-package :netcdf)

 (define-foreign-library libnetcdf
    (:unix "libnetcdf.so")
    (t (:default "libnetcdf")))

 (use-foreign-library libnetcdf)



;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cl:defconstant #.(swig-lispify "MPI_COMM_WORLD" 'constant) 0)

(cl:defconstant #.(swig-lispify "MPI_INFO_NULL" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_NAT" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_BYTE" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_CHAR" 'constant) 2)

(cl:defconstant #.(swig-lispify "NC_SHORT" 'constant) 3)

(cl:defconstant #.(swig-lispify "NC_INT" 'constant) 4)

(cl:defconstant #.(swig-lispify "NC_LONG" 'constant) 4)

(cl:defconstant #.(swig-lispify "NC_FLOAT" 'constant) 5)

(cl:defconstant #.(swig-lispify "NC_DOUBLE" 'constant) 6)

(cl:defconstant #.(swig-lispify "NC_UBYTE" 'constant) 7)

(cl:defconstant #.(swig-lispify "NC_USHORT" 'constant) 8)

(cl:defconstant #.(swig-lispify "NC_UINT" 'constant) 9)

(cl:defconstant #.(swig-lispify "NC_INT64" 'constant) 10)

(cl:defconstant #.(swig-lispify "NC_UINT64" 'constant) 11)

(cl:defconstant #.(swig-lispify "NC_STRING" 'constant) 12)

(cl:defconstant #.(swig-lispify "NC_VLEN" 'constant) 13)

(cl:defconstant #.(swig-lispify "NC_OPAQUE" 'constant) 14)

(cl:defconstant #.(swig-lispify "NC_ENUM" 'constant) 15)

(cl:defconstant #.(swig-lispify "NC_COMPOUND" 'constant) 16)

(cl:defconstant #.(swig-lispify "NC_FILL_INT" 'constant) -2147483647)

(cl:defconstant #.(swig-lispify "NC_FILL_FLOAT" 'constant) 9.9692099683868690d+36)

(cl:defconstant #.(swig-lispify "NC_FILL_DOUBLE" 'constant) 9.9692099683868690d+36)

(cl:defconstant #.(swig-lispify "NC_FILL_UBYTE" 'constant) 255)

(cl:defconstant #.(swig-lispify "NC_FILL_USHORT" 'constant) 65535)

(cl:defconstant #.(swig-lispify "NC_FILL_UINT" 'constant) 4294967295)


(cl:defconstant #.(swig-lispify "NC_MAX_BYTE" 'constant) 127)

(cl:defconstant #.(swig-lispify "NC_MIN_BYTE" 'constant) (cl:- 127 1))

(cl:defconstant #.(swig-lispify "NC_MAX_CHAR" 'constant) 255)

(cl:defconstant #.(swig-lispify "NC_MAX_SHORT" 'constant) 32767)

(cl:defconstant #.(swig-lispify "NC_MIN_SHORT" 'constant) (cl:- 32767 1))

(cl:defconstant #.(swig-lispify "NC_MAX_INT" 'constant) 2147483647)

(cl:defconstant #.(swig-lispify "NC_MIN_INT" 'constant) (cl:- 2147483647 1))

(cl:defconstant #.(swig-lispify "NC_MAX_FLOAT" 'constant) 3.402823466d+38)

(cl:defconstant #.(swig-lispify "NC_MIN_FLOAT" 'constant) -3.402823466d+38)

(cl:defconstant #.(swig-lispify "NC_MAX_DOUBLE" 'constant) 1.7976931348623157d+308)

(cl:defconstant #.(swig-lispify "NC_MIN_DOUBLE" 'constant) -1.7976931348623157d+308)

(cl:defconstant #.(swig-lispify "NC_MAX_UBYTE" 'constant) 255)

(cl:defconstant #.(swig-lispify "NC_MAX_USHORT" 'constant) 65535)

(cl:defconstant #.(swig-lispify "NC_MAX_UINT" 'constant) 4294967295)

(cl:defconstant #.(swig-lispify "NC_MAX_INT64" 'constant) 9223372036854775807)

(cl:defconstant #.(swig-lispify "NC_MIN_INT64" 'constant) (cl:- 9223372036854775807 1))

(cl:defconstant #.(swig-lispify "NC_MAX_UINT64" 'constant) 18446744073709551615)

(cl:defconstant #.(swig-lispify "X_INT64_MAX" 'constant) 9223372036854775807)

(cl:defconstant #.(swig-lispify "X_INT64_MIN" 'constant) (cl:- 9223372036854775807 1))

(cl:defconstant #.(swig-lispify "X_UINT64_MAX" 'constant) 18446744073709551615)


(cl:defconstant #.(swig-lispify "NC_FILL" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_NOFILL" 'constant) #x100)

(cl:defconstant #.(swig-lispify "NC_NOWRITE" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_WRITE" 'constant) #x0001)

(cl:defconstant #.(swig-lispify "NC_CLOBBER" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_NOCLOBBER" 'constant) #x0004)

(cl:defconstant #.(swig-lispify "NC_64BIT_OFFSET" 'constant) #x0200)

(cl:defconstant #.(swig-lispify "NC_NETCDF4" 'constant) #x1000)

(cl:defconstant #.(swig-lispify "NC_CLASSIC_MODEL" 'constant) #x0100)

(cl:defconstant #.(swig-lispify "NC_SHARE" 'constant) #x0800)

(cl:defconstant #.(swig-lispify "NC_MPIIO" 'constant) #x2000)

(cl:defconstant #.(swig-lispify "NC_MPIPOSIX" 'constant) #x4000)

(cl:defconstant #.(swig-lispify "NC_PNETCDF" 'constant) #x8000)

(cl:defconstant #.(swig-lispify "NC_LOCK" 'constant) #x0400)

(cl:defconstant #.(swig-lispify "NC_FORMAT_CLASSIC" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_FORMAT_64BIT" 'constant) 2)

(cl:defconstant #.(swig-lispify "NC_FORMAT_NETCDF4" 'constant) 3)

(cl:defconstant #.(swig-lispify "NC_FORMAT_NETCDF4_CLASSIC" 'constant) 4)

(cl:defconstant #.(swig-lispify "NC_SIZEHINT_DEFAULT" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_UNLIMITED" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_GLOBAL" 'constant) -1)

(cl:defconstant #.(swig-lispify "NC_MAX_DIMS" 'constant) 1024)

(cl:defconstant #.(swig-lispify "NC_MAX_ATTRS" 'constant) 8192)

(cl:defconstant #.(swig-lispify "NC_MAX_VARS" 'constant) 8192)

(cl:defconstant #.(swig-lispify "NC_MAX_NAME" 'constant) 256)

(cl:defconstant #.(swig-lispify "NC_MAX_VAR_DIMS" 'constant) 1024)

(cl:defconstant #.(swig-lispify "NC_ENDIAN_NATIVE" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_ENDIAN_LITTLE" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_ENDIAN_BIG" 'constant) 2)

(cl:defconstant #.(swig-lispify "NC_CHUNKED" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_CONTIGUOUS" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_NOCHECKSUM" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_FLETCHER32" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_NOSHUFFLE" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_SHUFFLE" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_NOERR" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC2_ERR" 'constant) -1)

(cl:defconstant #.(swig-lispify "NC_EBADID" 'constant) -33)

(cl:defconstant #.(swig-lispify "NC_ENFILE" 'constant) -34)

(cl:defconstant #.(swig-lispify "NC_EEXIST" 'constant) -35)

(cl:defconstant #.(swig-lispify "NC_EINVAL" 'constant) -36)

(cl:defconstant #.(swig-lispify "NC_EPERM" 'constant) -37)

(cl:defconstant #.(swig-lispify "NC_ENOTINDEFINE" 'constant) -38)

(cl:defconstant #.(swig-lispify "NC_EINDEFINE" 'constant) -39)

(cl:defconstant #.(swig-lispify "NC_EINVALCOORDS" 'constant) -40)

(cl:defconstant #.(swig-lispify "NC_EMAXDIMS" 'constant) -41)

(cl:defconstant #.(swig-lispify "NC_ENAMEINUSE" 'constant) -42)

(cl:defconstant #.(swig-lispify "NC_ENOTATT" 'constant) -43)

(cl:defconstant #.(swig-lispify "NC_EMAXATTS" 'constant) -44)

(cl:defconstant #.(swig-lispify "NC_EBADTYPE" 'constant) -45)

(cl:defconstant #.(swig-lispify "NC_EBADDIM" 'constant) -46)

(cl:defconstant #.(swig-lispify "NC_EUNLIMPOS" 'constant) -47)

(cl:defconstant #.(swig-lispify "NC_EMAXVARS" 'constant) -48)

(cl:defconstant #.(swig-lispify "NC_ENOTVAR" 'constant) -49)

(cl:defconstant #.(swig-lispify "NC_EGLOBAL" 'constant) -50)

(cl:defconstant #.(swig-lispify "NC_ENOTNC" 'constant) -51)

(cl:defconstant #.(swig-lispify "NC_ESTS" 'constant) -52)

(cl:defconstant #.(swig-lispify "NC_EMAXNAME" 'constant) -53)

(cl:defconstant #.(swig-lispify "NC_EUNLIMIT" 'constant) -54)

(cl:defconstant #.(swig-lispify "NC_ENORECVARS" 'constant) -55)

(cl:defconstant #.(swig-lispify "NC_ECHAR" 'constant) -56)

(cl:defconstant #.(swig-lispify "NC_EEDGE" 'constant) -57)

(cl:defconstant #.(swig-lispify "NC_ESTRIDE" 'constant) -58)

(cl:defconstant #.(swig-lispify "NC_EBADNAME" 'constant) -59)

(cl:defconstant #.(swig-lispify "NC_ERANGE" 'constant) -60)

(cl:defconstant #.(swig-lispify "NC_ENOMEM" 'constant) -61)

(cl:defconstant #.(swig-lispify "NC_EVARSIZE" 'constant) -62)

(cl:defconstant #.(swig-lispify "NC_EDIMSIZE" 'constant) -63)

(cl:defconstant #.(swig-lispify "NC_ETRUNC" 'constant) -64)

(cl:defconstant #.(swig-lispify "NC_EAXISTYPE" 'constant) -65)

(cl:defconstant #.(swig-lispify "NC_EDAP" 'constant) -66)

(cl:defconstant #.(swig-lispify "NC_ECURL" 'constant) -67)

(cl:defconstant #.(swig-lispify "NC_EIO" 'constant) -68)

(cl:defconstant #.(swig-lispify "NC_ENODATA" 'constant) -69)

(cl:defconstant #.(swig-lispify "NC_EDAPSVC" 'constant) -70)

(cl:defconstant #.(swig-lispify "NC_EDAS" 'constant) -71)

(cl:defconstant #.(swig-lispify "NC_EDDS" 'constant) -72)

(cl:defconstant #.(swig-lispify "NC_EDATADDS" 'constant) -73)

(cl:defconstant #.(swig-lispify "NC_EDAPURL" 'constant) -74)

(cl:defconstant #.(swig-lispify "NC_EDAPCONSTRAINT" 'constant) -75)

(cl:defconstant #.(swig-lispify "NC4_FIRST_ERROR" 'constant) -100)

(cl:defconstant #.(swig-lispify "NC_EHDFERR" 'constant) -101)

(cl:defconstant #.(swig-lispify "NC_ECANTREAD" 'constant) -102)

(cl:defconstant #.(swig-lispify "NC_ECANTWRITE" 'constant) -103)

(cl:defconstant #.(swig-lispify "NC_ECANTCREATE" 'constant) -104)

(cl:defconstant #.(swig-lispify "NC_EFILEMETA" 'constant) -105)

(cl:defconstant #.(swig-lispify "NC_EDIMMETA" 'constant) -106)

(cl:defconstant #.(swig-lispify "NC_EATTMETA" 'constant) -107)

(cl:defconstant #.(swig-lispify "NC_EVARMETA" 'constant) -108)

(cl:defconstant #.(swig-lispify "NC_ENOCOMPOUND" 'constant) -109)

(cl:defconstant #.(swig-lispify "NC_EATTEXISTS" 'constant) -110)

(cl:defconstant #.(swig-lispify "NC_ENOTNC4" 'constant) -111)

(cl:defconstant #.(swig-lispify "NC_ESTRICTNC3" 'constant) -112)

(cl:defconstant #.(swig-lispify "NC_ENOTNC3" 'constant) -113)

(cl:defconstant #.(swig-lispify "NC_ENOPAR" 'constant) -114)

(cl:defconstant #.(swig-lispify "NC_EPARINIT" 'constant) -115)

(cl:defconstant #.(swig-lispify "NC_EBADGRPID" 'constant) -116)

(cl:defconstant #.(swig-lispify "NC_EBADTYPID" 'constant) -117)

(cl:defconstant #.(swig-lispify "NC_ETYPDEFINED" 'constant) -118)

(cl:defconstant #.(swig-lispify "NC_EBADFIELD" 'constant) -119)

(cl:defconstant #.(swig-lispify "NC_EBADCLASS" 'constant) -120)

(cl:defconstant #.(swig-lispify "NC_EMAPTYPE" 'constant) -121)

(cl:defconstant #.(swig-lispify "NC_ELATEFILL" 'constant) -122)

(cl:defconstant #.(swig-lispify "NC_ELATEDEF" 'constant) -123)

(cl:defconstant #.(swig-lispify "NC_EDIMSCALE" 'constant) -124)

(cl:defconstant #.(swig-lispify "NC_ENOGRP" 'constant) -125)

(cl:defconstant #.(swig-lispify "NC_ESTORAGE" 'constant) -126)

(cl:defconstant #.(swig-lispify "NC_EBADCHUNK" 'constant) -127)

(cl:defconstant #.(swig-lispify "NC_ENOTBUILT" 'constant) -128)

(cl:defconstant #.(swig-lispify "NC4_LAST_ERROR" 'constant) -128)


(cl:defconstant #.(swig-lispify "NC_HAVE_NEW_CHUNKING_API" 'constant) 1)

(cffi:defcfun ("nc_inq_libvers" #.(swig-lispify "nc_inq_libvers" 'function)) :string)

(cffi:defcfun ("nc_strerror" #.(swig-lispify "nc_strerror" 'function)) :string
  (ncerr :int))

(cffi:defcfun ("nc__create" #.(swig-lispify "nc__create" 'function)) :int
  (path :string)
  (cmode :int)
  (initialsz :pointer)
  (chunksizehintp :pointer)
  (ncidp :pointer))

(cffi:defcfun ("nc_create" #.(swig-lispify "nc_create" 'function)) :int
  (path :string)
  (cmode :int)
  (ncidp :pointer))

(cffi:defcfun ("nc__open" #.(swig-lispify "nc__open" 'function)) :int
  (path :string)
  (mode :int)
  (chunksizehintp :pointer)
  (ncidp :pointer))

(cffi:defcfun ("nc_open" #.(swig-lispify "nc_open" 'function)) :int
  (path :string)
  (mode :int)
  (ncidp :pointer))

(cffi:defcfun ("nc_create_par" #.(swig-lispify "nc_create_par" 'function)) :int
  (path :string)
  (cmode :int)
  (comm :int)
  (info :int)
  (ncidp :pointer))

(cffi:defcfun ("nc_open_par" #.(swig-lispify "nc_open_par" 'function)) :int
  (path :string)
  (mode :int)
  (comm :int)
  (info :int)
  (ncidp :pointer))

(cl:defconstant #.(swig-lispify "NC_INDEPENDENT" 'constant) 0)

(cl:defconstant #.(swig-lispify "NC_COLLECTIVE" 'constant) 1)

(cffi:defcfun ("nc_var_par_access" #.(swig-lispify "nc_var_par_access" 'function)) :int
  (ncid :int)
  (varid :int)
  (par_access :int))

(cffi:defcfun ("nc_inq_ncid" #.(swig-lispify "nc_inq_ncid" 'function)) :int
  (ncid :int)
  (name :string)
  (grp_ncid :pointer))

(cffi:defcfun ("nc_inq_grps" #.(swig-lispify "nc_inq_grps" 'function)) :int
  (ncid :int)
  (numgrps :pointer)
  (ncids :pointer))

(cffi:defcfun ("nc_inq_grpname" #.(swig-lispify "nc_inq_grpname" 'function)) :int
  (ncid :int)
  (name :string))

(cffi:defcfun ("nc_inq_grpname_full" #.(swig-lispify "nc_inq_grpname_full" 'function)) :int
  (ncid :int)
  (lenp :pointer)
  (full_name :string))

(cffi:defcfun ("nc_inq_grpname_len" #.(swig-lispify "nc_inq_grpname_len" 'function)) :int
  (ncid :int)
  (lenp :pointer))

(cffi:defcfun ("nc_inq_grp_parent" #.(swig-lispify "nc_inq_grp_parent" 'function)) :int
  (ncid :int)
  (parent_ncid :pointer))

(cffi:defcfun ("nc_inq_grp_ncid" #.(swig-lispify "nc_inq_grp_ncid" 'function)) :int
  (ncid :int)
  (grp_name :string)
  (grp_ncid :pointer))

(cffi:defcfun ("nc_inq_grp_full_ncid" #.(swig-lispify "nc_inq_grp_full_ncid" 'function)) :int
  (ncid :int)
  (full_name :string)
  (grp_ncid :pointer))

(cffi:defcfun ("nc_inq_varids" #.(swig-lispify "nc_inq_varids" 'function)) :int
  (ncid :int)
  (nvars :pointer)
  (varids :pointer))

(cffi:defcfun ("nc_inq_dimids" #.(swig-lispify "nc_inq_dimids" 'function)) :int
  (ncid :int)
  (ndims :pointer)
  (dimids :pointer)
  (include_parents :int))

(cffi:defcfun ("nc_inq_typeids" #.(swig-lispify "nc_inq_typeids" 'function)) :int
  (ncid :int)
  (ntypes :pointer)
  (typeids :pointer))

(cffi:defcfun ("nc_inq_type_equal" #.(swig-lispify "nc_inq_type_equal" 'function)) :int
  (ncid1 :int)
  (typeid1 :int)
  (ncid2 :int)
  (typeid2 :int)
  (equal :pointer))

(cffi:defcfun ("nc_def_grp" #.(swig-lispify "nc_def_grp" 'function)) :int
  (parent_ncid :int)
  (name :string)
  (new_ncid :pointer))

(cffi:defcfun ("nc_def_compound" #.(swig-lispify "nc_def_compound" 'function)) :int
  (ncid :int)
  (size :pointer)
  (name :string)
  (typeidp :pointer))

(cffi:defcfun ("nc_insert_compound" #.(swig-lispify "nc_insert_compound" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (offset :pointer)
  (field_typeid :int))

(cffi:defcfun ("nc_insert_array_compound" #.(swig-lispify "nc_insert_array_compound" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (offset :pointer)
  (field_typeid :int)
  (ndims :int)
  (dim_sizes :pointer))

(cffi:defcfun ("nc_inq_type" #.(swig-lispify "nc_inq_type" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (size :pointer))

(cffi:defcfun ("nc_inq_typeid" #.(swig-lispify "nc_inq_typeid" 'function)) :int
  (ncid :int)
  (name :string)
  (typeidp :pointer))

(cffi:defcfun ("nc_inq_compound" #.(swig-lispify "nc_inq_compound" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (sizep :pointer)
  (nfieldsp :pointer))

(cffi:defcfun ("nc_inq_compound_name" #.(swig-lispify "nc_inq_compound_name" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string))

(cffi:defcfun ("nc_inq_compound_size" #.(swig-lispify "nc_inq_compound_size" 'function)) :int
  (ncid :int)
  (xtype :int)
  (sizep :pointer))

(cffi:defcfun ("nc_inq_compound_nfields" #.(swig-lispify "nc_inq_compound_nfields" 'function)) :int
  (ncid :int)
  (xtype :int)
  (nfieldsp :pointer))

(cffi:defcfun ("nc_inq_compound_field" #.(swig-lispify "nc_inq_compound_field" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (name :string)
  (offsetp :pointer)
  (field_typeidp :pointer)
  (ndimsp :pointer)
  (dim_sizesp :pointer))

(cffi:defcfun ("nc_inq_compound_fieldname" #.(swig-lispify "nc_inq_compound_fieldname" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (name :string))

(cffi:defcfun ("nc_inq_compound_fieldindex" #.(swig-lispify "nc_inq_compound_fieldindex" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (fieldidp :pointer))

(cffi:defcfun ("nc_inq_compound_fieldoffset" #.(swig-lispify "nc_inq_compound_fieldoffset" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (offsetp :pointer))

(cffi:defcfun ("nc_inq_compound_fieldtype" #.(swig-lispify "nc_inq_compound_fieldtype" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (field_typeidp :pointer))

(cffi:defcfun ("nc_inq_compound_fieldndims" #.(swig-lispify "nc_inq_compound_fieldndims" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (ndimsp :pointer))

(cffi:defcfun ("nc_inq_compound_fielddim_sizes" #.(swig-lispify "nc_inq_compound_fielddim_sizes" 'function)) :int
  (ncid :int)
  (xtype :int)
  (fieldid :int)
  (dim_sizes :pointer))

(cffi:defcstruct #.(swig-lispify "nc_vlen_t" 'classname)
	(#.(swig-lispify "len" 'slotname) :pointer)
	(#.(swig-lispify "p" 'slotname) :pointer))

(cffi:defcfun ("nc_def_vlen" #.(swig-lispify "nc_def_vlen" 'function)) :int
  (ncid :int)
  (name :string)
  (base_typeid :int)
  (xtypep :pointer))

(cffi:defcfun ("nc_inq_vlen" #.(swig-lispify "nc_inq_vlen" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (datum_sizep :pointer)
  (base_nc_typep :pointer))

(cffi:defcfun ("nc_free_vlen" #.(swig-lispify "nc_free_vlen" 'function)) :int
  (vl :pointer))

(cffi:defcfun ("nc_free_vlens" #.(swig-lispify "nc_free_vlens" 'function)) :int
  (len :pointer)
  (vlens :pointer))

(cffi:defcfun ("nc_put_vlen_element" #.(swig-lispify "nc_put_vlen_element" 'function)) :int
  (ncid :int)
  (typeid1 :int)
  (vlen_element :pointer)
  (len :pointer)
  (data :pointer))

(cffi:defcfun ("nc_get_vlen_element" #.(swig-lispify "nc_get_vlen_element" 'function)) :int
  (ncid :int)
  (typeid1 :int)
  (vlen_element :pointer)
  (len :pointer)
  (data :pointer))

(cffi:defcfun ("nc_free_string" #.(swig-lispify "nc_free_string" 'function)) :int
  (len :pointer)
  (data :pointer))

(cffi:defcfun ("nc_inq_user_type" #.(swig-lispify "nc_inq_user_type" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (size :pointer)
  (base_nc_typep :pointer)
  (nfieldsp :pointer)
  (classp :pointer))

(cffi:defcfun ("nc_put_att" #.(swig-lispify "nc_put_att" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att" #.(swig-lispify "nc_get_att" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_def_enum" #.(swig-lispify "nc_def_enum" 'function)) :int
  (ncid :int)
  (base_typeid :int)
  (name :string)
  (typeidp :pointer))

(cffi:defcfun ("nc_insert_enum" #.(swig-lispify "nc_insert_enum" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (value :pointer))

(cffi:defcfun ("nc_inq_enum" #.(swig-lispify "nc_inq_enum" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (base_nc_typep :pointer)
  (base_sizep :pointer)
  (num_membersp :pointer))

(cffi:defcfun ("nc_inq_enum_member" #.(swig-lispify "nc_inq_enum_member" 'function)) :int
  (ncid :int)
  (xtype :int)
  (idx :int)
  (name :string)
  (value :pointer))

(cffi:defcfun ("nc_inq_enum_ident" #.(swig-lispify "nc_inq_enum_ident" 'function)) :int
  (ncid :int)
  (xtype :int)
  (value :long-long)
  (identifier :string))

(cffi:defcfun ("nc_def_opaque" #.(swig-lispify "nc_def_opaque" 'function)) :int
  (ncid :int)
  (size :pointer)
  (name :string)
  (xtypep :pointer))

(cffi:defcfun ("nc_inq_opaque" #.(swig-lispify "nc_inq_opaque" 'function)) :int
  (ncid :int)
  (xtype :int)
  (name :string)
  (sizep :pointer))

(cffi:defcfun ("nc_put_var" #.(swig-lispify "nc_put_var" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var" #.(swig-lispify "nc_get_var" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1" #.(swig-lispify "nc_put_var1" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1" #.(swig-lispify "nc_get_var1" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara" #.(swig-lispify "nc_put_vara" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara" #.(swig-lispify "nc_get_vara" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars" #.(swig-lispify "nc_put_vars" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars" #.(swig-lispify "nc_get_vars" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm" #.(swig-lispify "nc_put_varm" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm" #.(swig-lispify "nc_get_varm" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_def_var_deflate" #.(swig-lispify "nc_def_var_deflate" 'function)) :int
  (ncid :int)
  (varid :int)
  (shuffle :int)
  (deflate :int)
  (deflate_level :int))

(cffi:defcfun ("nc_inq_var_deflate" #.(swig-lispify "nc_inq_var_deflate" 'function)) :int
  (ncid :int)
  (varid :int)
  (shufflep :pointer)
  (deflatep :pointer)
  (deflate_levelp :pointer))

(cffi:defcfun ("nc_inq_var_szip" #.(swig-lispify "nc_inq_var_szip" 'function)) :int
  (ncid :int)
  (varid :int)
  (options_maskp :pointer)
  (pixels_per_blockp :pointer))

(cffi:defcfun ("nc_def_var_fletcher32" #.(swig-lispify "nc_def_var_fletcher32" 'function)) :int
  (ncid :int)
  (varid :int)
  (fletcher32 :int))

(cffi:defcfun ("nc_inq_var_fletcher32" #.(swig-lispify "nc_inq_var_fletcher32" 'function)) :int
  (ncid :int)
  (varid :int)
  (fletcher32p :pointer))

(cffi:defcfun ("nc_def_var_chunking" #.(swig-lispify "nc_def_var_chunking" 'function)) :int
  (ncid :int)
  (varid :int)
  (storage :int)
  (chunksizesp :pointer))

(cffi:defcfun ("nc_inq_var_chunking" #.(swig-lispify "nc_inq_var_chunking" 'function)) :int
  (ncid :int)
  (varid :int)
  (storagep :pointer)
  (chunksizesp :pointer))

(cffi:defcfun ("nc_def_var_fill" #.(swig-lispify "nc_def_var_fill" 'function)) :int
  (ncid :int)
  (varid :int)
  (no_fill :int)
  (fill_value :pointer))

(cffi:defcfun ("nc_inq_var_fill" #.(swig-lispify "nc_inq_var_fill" 'function)) :int
  (ncid :int)
  (varid :int)
  (no_fill :pointer)
  (fill_value :pointer))

(cffi:defcfun ("nc_def_var_endian" #.(swig-lispify "nc_def_var_endian" 'function)) :int
  (ncid :int)
  (varid :int)
  (endian :int))

(cffi:defcfun ("nc_inq_var_endian" #.(swig-lispify "nc_inq_var_endian" 'function)) :int
  (ncid :int)
  (varid :int)
  (endianp :pointer))

(cffi:defcfun ("nc_set_fill" #.(swig-lispify "nc_set_fill" 'function)) :int
  (ncid :int)
  (fillmode :int)
  (old_modep :pointer))

(cffi:defcfun ("nc_set_default_format" #.(swig-lispify "nc_set_default_format" 'function)) :int
  (format :int)
  (old_formatp :pointer))

(cffi:defcfun ("nc_set_chunk_cache" #.(swig-lispify "nc_set_chunk_cache" 'function)) :int
  (size :pointer)
  (nelems :pointer)
  (preemption :float))

(cffi:defcfun ("nc_get_chunk_cache" #.(swig-lispify "nc_get_chunk_cache" 'function)) :int
  (sizep :pointer)
  (nelemsp :pointer)
  (preemptionp :pointer))

(cffi:defcfun ("nc_set_var_chunk_cache" #.(swig-lispify "nc_set_var_chunk_cache" 'function)) :int
  (ncid :int)
  (varid :int)
  (size :pointer)
  (nelems :pointer)
  (preemption :float))

(cffi:defcfun ("nc_get_var_chunk_cache" #.(swig-lispify "nc_get_var_chunk_cache" 'function)) :int
  (ncid :int)
  (varid :int)
  (sizep :pointer)
  (nelemsp :pointer)
  (preemptionp :pointer))

(cffi:defcfun ("nc_redef" #.(swig-lispify "nc_redef" 'function)) :int
  (ncid :int))

(cffi:defcfun ("nc__enddef" #.(swig-lispify "nc__enddef" 'function)) :int
  (ncid :int)
  (h_minfree :pointer)
  (v_align :pointer)
  (v_minfree :pointer)
  (r_align :pointer))

(cffi:defcfun ("nc_enddef" #.(swig-lispify "nc_enddef" 'function)) :int
  (ncid :int))

(cffi:defcfun ("nc_sync" #.(swig-lispify "nc_sync" 'function)) :int
  (ncid :int))

(cffi:defcfun ("nc_abort" #.(swig-lispify "nc_abort" 'function)) :int
  (ncid :int))

(cffi:defcfun ("nc_close" #.(swig-lispify "nc_close" 'function)) :int
  (ncid :int))

(cffi:defcfun ("nc_inq" #.(swig-lispify "nc_inq" 'function)) :int
  (ncid :int)
  (ndimsp :pointer)
  (nvarsp :pointer)
  (nattsp :pointer)
  (unlimdimidp :pointer))

(cffi:defcfun ("nc_inq_ndims" #.(swig-lispify "nc_inq_ndims" 'function)) :int
  (ncid :int)
  (ndimsp :pointer))

(cffi:defcfun ("nc_inq_nvars" #.(swig-lispify "nc_inq_nvars" 'function)) :int
  (ncid :int)
  (nvarsp :pointer))

(cffi:defcfun ("nc_inq_natts" #.(swig-lispify "nc_inq_natts" 'function)) :int
  (ncid :int)
  (nattsp :pointer))

(cffi:defcfun ("nc_inq_unlimdim" #.(swig-lispify "nc_inq_unlimdim" 'function)) :int
  (ncid :int)
  (unlimdimidp :pointer))

(cffi:defcfun ("nc_inq_unlimdims" #.(swig-lispify "nc_inq_unlimdims" 'function)) :int
  (ncid :int)
  (nunlimdimsp :pointer)
  (unlimdimidsp :pointer))

(cffi:defcfun ("nc_inq_format" #.(swig-lispify "nc_inq_format" 'function)) :int
  (ncid :int)
  (formatp :pointer))

(cffi:defcfun ("nc_def_dim" #.(swig-lispify "nc_def_dim" 'function)) :int
  (ncid :int)
  (name :string)
  (len :pointer)
  (idp :pointer))

(cffi:defcfun ("nc_inq_dimid" #.(swig-lispify "nc_inq_dimid" 'function)) :int
  (ncid :int)
  (name :string)
  (idp :pointer))

(cffi:defcfun ("nc_inq_dim" #.(swig-lispify "nc_inq_dim" 'function)) :int
  (ncid :int)
  (dimid :int)
  (name :string)
  (lenp :pointer))

(cffi:defcfun ("nc_inq_dimname" #.(swig-lispify "nc_inq_dimname" 'function)) :int
  (ncid :int)
  (dimid :int)
  (name :string))

(cffi:defcfun ("nc_inq_dimlen" #.(swig-lispify "nc_inq_dimlen" 'function)) :int
  (ncid :int)
  (dimid :int)
  (lenp :pointer))

(cffi:defcfun ("nc_rename_dim" #.(swig-lispify "nc_rename_dim" 'function)) :int
  (ncid :int)
  (dimid :int)
  (name :string))

(cffi:defcfun ("nc_inq_att" #.(swig-lispify "nc_inq_att" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtypep :pointer)
  (lenp :pointer))

(cffi:defcfun ("nc_inq_attid" #.(swig-lispify "nc_inq_attid" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (idp :pointer))

(cffi:defcfun ("nc_inq_atttype" #.(swig-lispify "nc_inq_atttype" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtypep :pointer))

(cffi:defcfun ("nc_inq_attlen" #.(swig-lispify "nc_inq_attlen" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (lenp :pointer))

(cffi:defcfun ("nc_inq_attname" #.(swig-lispify "nc_inq_attname" 'function)) :int
  (ncid :int)
  (varid :int)
  (attnum :int)
  (name :string))

(cffi:defcfun ("nc_copy_att" #.(swig-lispify "nc_copy_att" 'function)) :int
  (ncid_in :int)
  (varid_in :int)
  (name :string)
  (ncid_out :int)
  (varid_out :int))

(cffi:defcfun ("nc_rename_att" #.(swig-lispify "nc_rename_att" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (newname :string))

(cffi:defcfun ("nc_del_att" #.(swig-lispify "nc_del_att" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string))

(cffi:defcfun ("nc_put_att_text" #.(swig-lispify "nc_put_att_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (len :pointer)
  (op :string))

(cffi:defcfun ("nc_get_att_text" #.(swig-lispify "nc_get_att_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :string))

(cffi:defcfun ("nc_put_att_uchar" #.(swig-lispify "nc_put_att_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_uchar" #.(swig-lispify "nc_get_att_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_schar" #.(swig-lispify "nc_put_att_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_schar" #.(swig-lispify "nc_get_att_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_short" #.(swig-lispify "nc_put_att_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_short" #.(swig-lispify "nc_get_att_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_int" #.(swig-lispify "nc_put_att_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_int" #.(swig-lispify "nc_get_att_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_long" #.(swig-lispify "nc_put_att_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_long" #.(swig-lispify "nc_get_att_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_float" #.(swig-lispify "nc_put_att_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_float" #.(swig-lispify "nc_get_att_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_double" #.(swig-lispify "nc_put_att_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_double" #.(swig-lispify "nc_get_att_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_ubyte" #.(swig-lispify "nc_put_att_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_ubyte" #.(swig-lispify "nc_get_att_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_ushort" #.(swig-lispify "nc_put_att_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_ushort" #.(swig-lispify "nc_get_att_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_uint" #.(swig-lispify "nc_put_att_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_uint" #.(swig-lispify "nc_get_att_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_longlong" #.(swig-lispify "nc_put_att_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_longlong" #.(swig-lispify "nc_get_att_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_ulonglong" #.(swig-lispify "nc_put_att_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_ulonglong" #.(swig-lispify "nc_get_att_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_put_att_string" #.(swig-lispify "nc_put_att_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (len :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_att_string" #.(swig-lispify "nc_get_att_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("nc_def_var" #.(swig-lispify "nc_def_var" 'function)) :int
  (ncid :int)
  (name :string)
  (xtype :int)
  (ndims :int)
  (dimidsp :pointer)
  (varidp :pointer))

(cffi:defcfun ("nc_inq_var" #.(swig-lispify "nc_inq_var" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtypep :pointer)
  (ndimsp :pointer)
  (dimidsp :pointer)
  (nattsp :pointer))

(cffi:defcfun ("nc_inq_varid" #.(swig-lispify "nc_inq_varid" 'function)) :int
  (ncid :int)
  (name :string)
  (varidp :pointer))

(cffi:defcfun ("nc_inq_varname" #.(swig-lispify "nc_inq_varname" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string))

(cffi:defcfun ("nc_inq_vartype" #.(swig-lispify "nc_inq_vartype" 'function)) :int
  (ncid :int)
  (varid :int)
  (xtypep :pointer))

(cffi:defcfun ("nc_inq_varndims" #.(swig-lispify "nc_inq_varndims" 'function)) :int
  (ncid :int)
  (varid :int)
  (ndimsp :pointer))

(cffi:defcfun ("nc_inq_vardimid" #.(swig-lispify "nc_inq_vardimid" 'function)) :int
  (ncid :int)
  (varid :int)
  (dimidsp :pointer))

(cffi:defcfun ("nc_inq_varnatts" #.(swig-lispify "nc_inq_varnatts" 'function)) :int
  (ncid :int)
  (varid :int)
  (nattsp :pointer))

(cffi:defcfun ("nc_rename_var" #.(swig-lispify "nc_rename_var" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string))

(cffi:defcfun ("nc_copy_var" #.(swig-lispify "nc_copy_var" 'function)) :int
  (ncid_in :int)
  (varid :int)
  (ncid_out :int))

(cffi:defcfun ("nc_put_var1_text" #.(swig-lispify "nc_put_var1_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :string))

(cffi:defcfun ("nc_get_var1_text" #.(swig-lispify "nc_get_var1_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :string))

(cffi:defcfun ("nc_put_var1_uchar" #.(swig-lispify "nc_put_var1_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_uchar" #.(swig-lispify "nc_get_var1_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_schar" #.(swig-lispify "nc_put_var1_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_schar" #.(swig-lispify "nc_get_var1_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_short" #.(swig-lispify "nc_put_var1_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_short" #.(swig-lispify "nc_get_var1_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_int" #.(swig-lispify "nc_put_var1_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_int" #.(swig-lispify "nc_get_var1_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_long" #.(swig-lispify "nc_put_var1_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_long" #.(swig-lispify "nc_get_var1_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_float" #.(swig-lispify "nc_put_var1_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_float" #.(swig-lispify "nc_get_var1_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_double" #.(swig-lispify "nc_put_var1_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_double" #.(swig-lispify "nc_get_var1_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_ubyte" #.(swig-lispify "nc_put_var1_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_ubyte" #.(swig-lispify "nc_get_var1_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_ushort" #.(swig-lispify "nc_put_var1_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_ushort" #.(swig-lispify "nc_get_var1_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_uint" #.(swig-lispify "nc_put_var1_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_uint" #.(swig-lispify "nc_get_var1_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_longlong" #.(swig-lispify "nc_put_var1_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_longlong" #.(swig-lispify "nc_get_var1_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_ulonglong" #.(swig-lispify "nc_put_var1_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_ulonglong" #.(swig-lispify "nc_get_var1_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var1_string" #.(swig-lispify "nc_put_var1_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_var1_string" #.(swig-lispify "nc_get_var1_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_text" #.(swig-lispify "nc_put_vara_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :string))

(cffi:defcfun ("nc_get_vara_text" #.(swig-lispify "nc_get_vara_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :string))

(cffi:defcfun ("nc_put_vara_uchar" #.(swig-lispify "nc_put_vara_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_uchar" #.(swig-lispify "nc_get_vara_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_schar" #.(swig-lispify "nc_put_vara_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_schar" #.(swig-lispify "nc_get_vara_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_short" #.(swig-lispify "nc_put_vara_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_short" #.(swig-lispify "nc_get_vara_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_int" #.(swig-lispify "nc_put_vara_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_int" #.(swig-lispify "nc_get_vara_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_long" #.(swig-lispify "nc_put_vara_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_long" #.(swig-lispify "nc_get_vara_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_float" #.(swig-lispify "nc_put_vara_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_float" #.(swig-lispify "nc_get_vara_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_double" #.(swig-lispify "nc_put_vara_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_double" #.(swig-lispify "nc_get_vara_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_ubyte" #.(swig-lispify "nc_put_vara_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_ubyte" #.(swig-lispify "nc_get_vara_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_ushort" #.(swig-lispify "nc_put_vara_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_ushort" #.(swig-lispify "nc_get_vara_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_uint" #.(swig-lispify "nc_put_vara_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_uint" #.(swig-lispify "nc_get_vara_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_longlong" #.(swig-lispify "nc_put_vara_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_longlong" #.(swig-lispify "nc_get_vara_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_ulonglong" #.(swig-lispify "nc_put_vara_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_ulonglong" #.(swig-lispify "nc_get_vara_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vara_string" #.(swig-lispify "nc_put_vara_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vara_string" #.(swig-lispify "nc_get_vara_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_text" #.(swig-lispify "nc_put_vars_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :string))

(cffi:defcfun ("nc_get_vars_text" #.(swig-lispify "nc_get_vars_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :string))

(cffi:defcfun ("nc_put_vars_uchar" #.(swig-lispify "nc_put_vars_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_uchar" #.(swig-lispify "nc_get_vars_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_schar" #.(swig-lispify "nc_put_vars_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_schar" #.(swig-lispify "nc_get_vars_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_short" #.(swig-lispify "nc_put_vars_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_short" #.(swig-lispify "nc_get_vars_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_int" #.(swig-lispify "nc_put_vars_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_int" #.(swig-lispify "nc_get_vars_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_long" #.(swig-lispify "nc_put_vars_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_long" #.(swig-lispify "nc_get_vars_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_float" #.(swig-lispify "nc_put_vars_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_float" #.(swig-lispify "nc_get_vars_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_double" #.(swig-lispify "nc_put_vars_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_double" #.(swig-lispify "nc_get_vars_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_ubyte" #.(swig-lispify "nc_put_vars_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_ubyte" #.(swig-lispify "nc_get_vars_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_ushort" #.(swig-lispify "nc_put_vars_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_ushort" #.(swig-lispify "nc_get_vars_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_uint" #.(swig-lispify "nc_put_vars_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_uint" #.(swig-lispify "nc_get_vars_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_longlong" #.(swig-lispify "nc_put_vars_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_longlong" #.(swig-lispify "nc_get_vars_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_ulonglong" #.(swig-lispify "nc_put_vars_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_ulonglong" #.(swig-lispify "nc_get_vars_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_vars_string" #.(swig-lispify "nc_put_vars_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_vars_string" #.(swig-lispify "nc_get_vars_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_text" #.(swig-lispify "nc_put_varm_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :string))

(cffi:defcfun ("nc_get_varm_text" #.(swig-lispify "nc_get_varm_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :string))

(cffi:defcfun ("nc_put_varm_uchar" #.(swig-lispify "nc_put_varm_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_uchar" #.(swig-lispify "nc_get_varm_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_schar" #.(swig-lispify "nc_put_varm_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_schar" #.(swig-lispify "nc_get_varm_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_short" #.(swig-lispify "nc_put_varm_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_short" #.(swig-lispify "nc_get_varm_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_int" #.(swig-lispify "nc_put_varm_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_int" #.(swig-lispify "nc_get_varm_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_long" #.(swig-lispify "nc_put_varm_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_long" #.(swig-lispify "nc_get_varm_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_float" #.(swig-lispify "nc_put_varm_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_float" #.(swig-lispify "nc_get_varm_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_double" #.(swig-lispify "nc_put_varm_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_double" #.(swig-lispify "nc_get_varm_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_ubyte" #.(swig-lispify "nc_put_varm_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_ubyte" #.(swig-lispify "nc_get_varm_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_ushort" #.(swig-lispify "nc_put_varm_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_ushort" #.(swig-lispify "nc_get_varm_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_uint" #.(swig-lispify "nc_put_varm_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_uint" #.(swig-lispify "nc_get_varm_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_longlong" #.(swig-lispify "nc_put_varm_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_longlong" #.(swig-lispify "nc_get_varm_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_ulonglong" #.(swig-lispify "nc_put_varm_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_ulonglong" #.(swig-lispify "nc_get_varm_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_varm_string" #.(swig-lispify "nc_put_varm_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("nc_get_varm_string" #.(swig-lispify "nc_get_varm_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_text" #.(swig-lispify "nc_put_var_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :string))

(cffi:defcfun ("nc_get_var_text" #.(swig-lispify "nc_get_var_text" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :string))

(cffi:defcfun ("nc_put_var_uchar" #.(swig-lispify "nc_put_var_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_uchar" #.(swig-lispify "nc_get_var_uchar" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_schar" #.(swig-lispify "nc_put_var_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_schar" #.(swig-lispify "nc_get_var_schar" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_short" #.(swig-lispify "nc_put_var_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_short" #.(swig-lispify "nc_get_var_short" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_int" #.(swig-lispify "nc_put_var_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_int" #.(swig-lispify "nc_get_var_int" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_long" #.(swig-lispify "nc_put_var_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_long" #.(swig-lispify "nc_get_var_long" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_float" #.(swig-lispify "nc_put_var_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_float" #.(swig-lispify "nc_get_var_float" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_double" #.(swig-lispify "nc_put_var_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_double" #.(swig-lispify "nc_get_var_double" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_ubyte" #.(swig-lispify "nc_put_var_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_ubyte" #.(swig-lispify "nc_get_var_ubyte" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_ushort" #.(swig-lispify "nc_put_var_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_ushort" #.(swig-lispify "nc_get_var_ushort" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_uint" #.(swig-lispify "nc_put_var_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_uint" #.(swig-lispify "nc_get_var_uint" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_longlong" #.(swig-lispify "nc_put_var_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_longlong" #.(swig-lispify "nc_get_var_longlong" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_ulonglong" #.(swig-lispify "nc_put_var_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_ulonglong" #.(swig-lispify "nc_get_var_ulonglong" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc_put_var_string" #.(swig-lispify "nc_put_var_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (op :pointer))

(cffi:defcfun ("nc_get_var_string" #.(swig-lispify "nc_get_var_string" 'function)) :int
  (ncid :int)
  (varid :int)
  (ip :pointer))

(cffi:defcfun ("nc__create_mp" #.(swig-lispify "nc__create_mp" 'function)) :int
  (path :string)
  (cmode :int)
  (initialsz :pointer)
  (basepe :int)
  (chunksizehintp :pointer)
  (ncidp :pointer))

(cffi:defcfun ("nc__open_mp" #.(swig-lispify "nc__open_mp" 'function)) :int
  (path :string)
  (mode :int)
  (basepe :int)
  (chunksizehintp :pointer)
  (ncidp :pointer))

(cffi:defcfun ("nc_delete" #.(swig-lispify "nc_delete" 'function)) :int
  (path :string))

(cffi:defcfun ("nc_delete_mp" #.(swig-lispify "nc_delete_mp" 'function)) :int
  (path :string)
  (basepe :int))

(cffi:defcfun ("nc_set_base_pe" #.(swig-lispify "nc_set_base_pe" 'function)) :int
  (ncid :int)
  (pe :int))

(cffi:defcfun ("nc_inq_base_pe" #.(swig-lispify "nc_inq_base_pe" 'function)) :int
  (ncid :int)
  (pe :pointer))

(cl:defconstant #.(swig-lispify "FILL_LONG" 'constant) -2147483647)

(cl:defconstant #.(swig-lispify "FILL_FLOAT" 'constant) 9.9692099683868690d+36)

(cl:defconstant #.(swig-lispify "FILL_DOUBLE" 'constant) 9.9692099683868690d+36)

(cl:defconstant #.(swig-lispify "MAX_NC_DIMS" 'constant) 1024)

(cl:defconstant #.(swig-lispify "MAX_NC_ATTRS" 'constant) 8192)

(cl:defconstant #.(swig-lispify "MAX_NC_VARS" 'constant) 8192)

(cl:defconstant #.(swig-lispify "MAX_NC_NAME" 'constant) 256)

(cl:defconstant #.(swig-lispify "MAX_VAR_DIMS" 'constant) 1024)

(cffi:defcvar ("ncerr" #.(swig-lispify "ncerr" 'variable))
 :int)

(cl:defconstant #.(swig-lispify "NC_ENTOOL" 'constant) -53)

(cl:defconstant #.(swig-lispify "NC_EXDR" 'constant) -32)

(cl:defconstant #.(swig-lispify "NC_SYSERR" 'constant) -31)

(cl:defconstant #.(swig-lispify "NC_FATAL" 'constant) 1)

(cl:defconstant #.(swig-lispify "NC_VERBOSE" 'constant) 2)

(cffi:defcvar ("ncopts" #.(swig-lispify "ncopts" 'variable))
 :int)

(cffi:defcfun ("nc_advise" #.(swig-lispify "nc_advise" 'function)) :void
  (cdf_routine_name :string)
  (err :int)
  (fmt :string)
  &rest)

(cffi:defcfun ("nctypelen" #.(swig-lispify "nctypelen" 'function)) :int
  (datatype :int))

(cffi:defcfun ("nccreate" #.(swig-lispify "nccreate" 'function)) :int
  (path :string)
  (cmode :int))

(cffi:defcfun ("ncopen" #.(swig-lispify "ncopen" 'function)) :int
  (path :string)
  (mode :int))

(cffi:defcfun ("ncsetfill" #.(swig-lispify "ncsetfill" 'function)) :int
  (ncid :int)
  (fillmode :int))

(cffi:defcfun ("ncredef" #.(swig-lispify "ncredef" 'function)) :int
  (ncid :int))

(cffi:defcfun ("ncendef" #.(swig-lispify "ncendef" 'function)) :int
  (ncid :int))

(cffi:defcfun ("ncsync" #.(swig-lispify "ncsync" 'function)) :int
  (ncid :int))

(cffi:defcfun ("ncabort" #.(swig-lispify "ncabort" 'function)) :int
  (ncid :int))

(cffi:defcfun ("ncclose" #.(swig-lispify "ncclose" 'function)) :int
  (ncid :int))

(cffi:defcfun ("ncinquire" #.(swig-lispify "ncinquire" 'function)) :int
  (ncid :int)
  (ndimsp :pointer)
  (nvarsp :pointer)
  (nattsp :pointer)
  (unlimdimp :pointer))

(cffi:defcfun ("ncdimdef" #.(swig-lispify "ncdimdef" 'function)) :int
  (ncid :int)
  (name :string)
  (len :long))

(cffi:defcfun ("ncdimid" #.(swig-lispify "ncdimid" 'function)) :int
  (ncid :int)
  (name :string))

(cffi:defcfun ("ncdiminq" #.(swig-lispify "ncdiminq" 'function)) :int
  (ncid :int)
  (dimid :int)
  (name :string)
  (lenp :pointer))

(cffi:defcfun ("ncdimrename" #.(swig-lispify "ncdimrename" 'function)) :int
  (ncid :int)
  (dimid :int)
  (name :string))

(cffi:defcfun ("ncattput" #.(swig-lispify "ncattput" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtype :int)
  (len :int)
  (op :pointer))

(cffi:defcfun ("ncattinq" #.(swig-lispify "ncattinq" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtypep :pointer)
  (lenp :pointer))

(cffi:defcfun ("ncattget" #.(swig-lispify "ncattget" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (ip :pointer))

(cffi:defcfun ("ncattcopy" #.(swig-lispify "ncattcopy" 'function)) :int
  (ncid_in :int)
  (varid_in :int)
  (name :string)
  (ncid_out :int)
  (varid_out :int))

(cffi:defcfun ("ncattname" #.(swig-lispify "ncattname" 'function)) :int
  (ncid :int)
  (varid :int)
  (attnum :int)
  (name :string))

(cffi:defcfun ("ncattrename" #.(swig-lispify "ncattrename" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (newname :string))

(cffi:defcfun ("ncattdel" #.(swig-lispify "ncattdel" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string))

(cffi:defcfun ("ncvardef" #.(swig-lispify "ncvardef" 'function)) :int
  (ncid :int)
  (name :string)
  (xtype :int)
  (ndims :int)
  (dimidsp :pointer))

(cffi:defcfun ("ncvarid" #.(swig-lispify "ncvarid" 'function)) :int
  (ncid :int)
  (name :string))

(cffi:defcfun ("ncvarinq" #.(swig-lispify "ncvarinq" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string)
  (xtypep :pointer)
  (ndimsp :pointer)
  (dimidsp :pointer)
  (nattsp :pointer))

(cffi:defcfun ("ncvarput1" #.(swig-lispify "ncvarput1" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (op :pointer))

(cffi:defcfun ("ncvarget1" #.(swig-lispify "ncvarget1" 'function)) :int
  (ncid :int)
  (varid :int)
  (indexp :pointer)
  (ip :pointer))

(cffi:defcfun ("ncvarput" #.(swig-lispify "ncvarput" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (op :pointer))

(cffi:defcfun ("ncvarget" #.(swig-lispify "ncvarget" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (ip :pointer))

(cffi:defcfun ("ncvarputs" #.(swig-lispify "ncvarputs" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (op :pointer))

(cffi:defcfun ("ncvargets" #.(swig-lispify "ncvargets" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (ip :pointer))

(cffi:defcfun ("ncvarputg" #.(swig-lispify "ncvarputg" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (op :pointer))

(cffi:defcfun ("ncvargetg" #.(swig-lispify "ncvargetg" 'function)) :int
  (ncid :int)
  (varid :int)
  (startp :pointer)
  (countp :pointer)
  (stridep :pointer)
  (imapp :pointer)
  (ip :pointer))

(cffi:defcfun ("ncvarrename" #.(swig-lispify "ncvarrename" 'function)) :int
  (ncid :int)
  (varid :int)
  (name :string))

(cffi:defcfun ("ncrecinq" #.(swig-lispify "ncrecinq" 'function)) :int
  (ncid :int)
  (nrecvarsp :pointer)
  (recvaridsp :pointer)
  (recsizesp :pointer))

(cffi:defcfun ("ncrecget" #.(swig-lispify "ncrecget" 'function)) :int
  (ncid :int)
  (recnum :long)
  (datap :pointer))

(cffi:defcfun ("ncrecput" #.(swig-lispify "ncrecput" 'function)) :int
  (ncid :int)
  (recnum :long)
  (datap :pointer))


