
(defun nctest ()
  (cffi:with-foreign-objects ((ncid :int)
			      (x-dimid :int)
			      (y-dimid :int)
			      (dimsid :int 2)
			      (varid :int)
			      )
    (netcdf::nc-create "/tmp/x.cdf" netcdf::+nc-clobber+ ncid)
    (netcdf::nc-def-dim (cffi:mem-ref ncid :int) "x" (cffi:make-pointer 17) x-dimid)
    (netcdf::nc-def-dim (cffi:mem-ref ncid :int) "yy" (cffi:make-pointer 7) y-dimid)
    (setf (cffi:mem-aref dimsid :int 0) (cffi:mem-ref x-dimid :int))
    (setf (cffi:mem-aref dimsid :int 1) (cffi:mem-ref y-dimid :int))
    (netcdf::nc-def-var (cffi:mem-ref ncid :int) "data" netcdf::+nc-int+ 2 dimsid varid)

    (netcdf::nc-enddef (cffi:mem-ref ncid :int))
    (netcdf::nc-close (cffi:mem-ref ncid :int))
    ))